"""Render triage results as markdown (SUITABILITY.md-compatible) and JSON.

The markdown front-matter intentionally uses the SAME schema keys as the
hand-written ``projects/*/SUITABILITY.md`` files, so the existing
``scripts/build_triage.R`` aggregator consumes CLI-generated reports unchanged.
Extra CLI-only keys (score, class, warnings, factors, next_action) are added
after; the R aggregator ignores unknown keys.
"""

from __future__ import annotations

import json
from typing import List

from .parse import GeoMetadata
from .suitability import Suitability, orgdb_for


def _q(s: str) -> str:
    """Quote a scalar for YAML (and escape embedded quotes)."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _yaml_list_inline_dicts(items: List[dict]) -> List[str]:
    out = []
    for it in items:
        inner = ", ".join(f"{k}: {_q(v) if isinstance(v, str) else v}" for k, v in it.items())
        out.append(f"  - {{{inner}}}")
    return out


def build_record(meta: GeoMetadata, suit: Suitability) -> dict:
    """A single structured dict that backs both JSON and markdown output."""
    return {
        "accession": meta.accession,
        "title": meta.title,
        "organism": meta.organisms[0] if meta.organisms else "",
        "organisms": meta.organisms,
        "assay_type": {"rna_seq": "bulk RNA-seq", "microarray": "microarray",
                       "single_cell": "single-cell RNA-seq", "other": "unknown"}.get(suit.assay, suit.assay),
        "platform": meta.platform_title or meta.platform_id,
        "series_type": meta.series_type,
        "n_samples": meta.n_samples,
        "processed_files": suit.processed_files,
        "raw_counts_available": suit.raw_counts_available,
        "normalized_values_present": suit.normalized_values_present,
        "groups": suit.groups,
        "min_replicates_per_group": suit.min_replicates_per_group,
        "metadata_clarity": suit.metadata_clarity,
        "possible_contrasts": suit.possible_contrasts,
        "recommended_design": suit.recommended_design,
        "de_method": suit.de_method,
        "decision": suit.decision,
        "organism_db": orgdb_for(meta),
        # --- CLI-specific transparency fields ---
        "suitability_class": suit.suitability_class,
        "suitability_score": suit.score,
        "score_reasons": suit.reasons,
        "warnings": suit.warnings,
        "factors": [
            {"factor": f.name, "source_key": f.source_key, "levels": f.levels,
             "ambiguous": f.ambiguous, "note": f.note}
            for f in suit.factors
        ],
        "next_action": suit.next_action,
        "generated_by": "geo_portfolio CLI",
    }


def to_json(meta: GeoMetadata, suit: Suitability, indent: int = 2) -> str:
    return json.dumps(build_record(meta, suit), indent=indent, ensure_ascii=False)


def to_markdown(meta: GeoMetadata, suit: Suitability) -> str:
    rec = build_record(meta, suit)
    fm: List[str] = ["---"]
    fm.append(f"accession: {rec['accession']}")
    fm.append(f"title: {_q(rec['title'])}")
    fm.append(f"organism: {_q(rec['organism'])}")
    fm.append(f"assay_type: {_q(rec['assay_type'])}")
    fm.append(f"platform: {_q(rec['platform'])}")
    fm.append(f"n_samples: {rec['n_samples']}")
    fm.append("processed_files:" + (" []" if not rec["processed_files"] else ""))
    fm += _yaml_list_inline_dicts(rec["processed_files"])
    fm.append(f"raw_counts_available: {_q(rec['raw_counts_available'])}")
    fm.append(f"normalized_values_present: {_q(rec['normalized_values_present'])}")
    fm.append("groups:" + (" []" if not rec["groups"] else ""))
    fm += _yaml_list_inline_dicts(rec["groups"])
    fm.append(f"min_replicates_per_group: {rec['min_replicates_per_group']}")
    fm.append(f"metadata_clarity: {rec['metadata_clarity']}")
    fm.append("possible_contrasts:" + (" []" if not rec["possible_contrasts"] else ""))
    fm += [f"  - {_q(c)}" for c in rec["possible_contrasts"]]
    fm.append(f"recommended_design: {_q(rec['recommended_design'])}")
    fm.append(f"de_method: {_q(rec['de_method'])}")
    fm.append(f"decision: {rec['decision']}")
    fm.append(f"suitability_class: {rec['suitability_class']}")
    fm.append(f"suitability_score: {rec['suitability_score']}")
    fm.append("decision_reasons:")
    fm += [f"  - {_q(r['text'])}" for r in rec["score_reasons"] if r["delta"] != 0] or ["  - \"see scoring below\""]
    fm.append("generated_by: geo_portfolio CLI")
    fm.append("---")

    cls = rec["suitability_class"].replace("_", " ").upper()
    body: List[str] = [
        "",
        f"# Dataset suitability report — {rec['accession']}",
        "",
        f"> **{cls}** (score {rec['suitability_score']}/100, decision: `{rec['decision']}`). "
        f"Auto-generated by the `geo` CLI; review before relying on it.",
        "",
        "## Identity",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Accession | {rec['accession']} |",
        f"| Title | {rec['title']} |",
        f"| Organism | {rec['organism']} |",
        f"| Assay | {rec['assay_type']} ({rec['series_type']}) |",
        f"| Platform | {rec['platform']} |",
        f"| Samples | {rec['n_samples']} |",
        "",
        "## Data type",
        "",
        f"- Raw counts available: **{rec['raw_counts_available']}**",
        f"- Normalized (FPKM/TPM/…) present: **{rec['normalized_values_present']}**",
        f"- Recommended DE method: **{rec['de_method']}**",
        "",
        "### Supplementary files",
        "",
        "| File | Classified as |",
        "|------|---------------|",
    ]
    body += [f"| {f['name']} | {f['type']} |" for f in rec["processed_files"]] or ["| _none_ | — |"]
    body += ["", "## Inferred factors", ""]
    if rec["factors"]:
        body += ["| Factor | Characteristics key | Levels | Ambiguous |",
                 "|--------|--------------------|--------|-----------|"]
        for f in rec["factors"]:
            lv = ", ".join(f"{k} (n={v})" for k, v in f["levels"].items()) or "—"
            body.append(f"| {f['factor']} | {f['source_key']} | {lv} | {'yes' if f['ambiguous'] else 'no'} |")
    else:
        body.append("_No grouping factors could be inferred from sample characteristics._")

    body += ["", "## Suitability scoring", "", "| Δ | Reason |", "|---|--------|"]
    body += [f"| {r['delta']:+d} | {r['text']} |" for r in rec["score_reasons"]]
    body += [f"| = | **Total: {rec['suitability_score']}/100 → {cls}** |"]

    if rec["warnings"]:
        body += ["", "## Warnings", ""] + [f"- ⚠️ {w}" for w in rec["warnings"]]

    body += [
        "",
        "## Recommended design & next action",
        "",
        f"- Design formula: `{rec['recommended_design']}`",
        f"- Possible contrasts: {', '.join(rec['possible_contrasts']) or '— (manual review)'}",
        f"- **Next action:** {rec['next_action']}",
        "",
        "## Assumptions & limitations",
        "",
        "- Group labels are read from GEO `characteristics_ch1` fields, never inferred from free-text titles.",
        "- Ambiguous or unique-per-sample characteristics are flagged, not guessed.",
        "- This report is metadata-only; it does not download or inspect the count matrix values.",
        "",
    ]
    return "\n".join(fm + body)
