#!/usr/bin/env Rscript
# build_triage.R
# Aggregate every project's SUITABILITY.md front-matter into a single
# cross-dataset triage table (docs/TRIAGE.md + docs/triage.csv).
#
# Usage (from repo root):  Rscript scripts/build_triage.R
#
# This is the "judgment across datasets" layer: it makes include/exclude
# decisions and their rationale comparable at a glance.

suppressPackageStartupMessages(library(yaml))
`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

read_frontmatter <- function(path) {
  lines <- readLines(path, warn = FALSE)
  fences <- which(trimws(lines) == "---")
  if (length(fences) < 2) {
    warning("No YAML front-matter in ", path); return(NULL)
  }
  block <- lines[(fences[1] + 1):(fences[2] - 1)]
  yaml::yaml.load(paste(block, collapse = "\n"))
}

scalar <- function(x) if (is.null(x) || length(x) == 0) NA_character_ else as.character(x)[1]

files <- Sys.glob("projects/*/SUITABILITY.md")
if (length(files) == 0) stop("No projects/*/SUITABILITY.md found (run from repo root).")

rows <- lapply(files, function(f) {
  fm <- read_frontmatter(f)
  if (is.null(fm)) return(NULL)
  data.frame(
    accession    = scalar(fm$accession),
    organism     = scalar(fm$organism),
    assay        = scalar(fm$assay_type),
    n_samples    = scalar(fm$n_samples),
    min_reps     = scalar(fm$min_replicates_per_group),
    raw_counts   = scalar(fm$raw_counts_available),
    normalized   = scalar(fm$normalized_values_present),
    metadata     = scalar(fm$metadata_clarity),
    design       = scalar(fm$recommended_design),
    method       = scalar(fm$de_method),
    decision     = scalar(fm$decision),
    reason       = scalar((fm$decision_reasons %||% list(NA))[[1]]),
    stringsAsFactors = FALSE)
})
tab <- do.call(rbind, Filter(Negate(is.null), rows))
# Order decisions meaningfully (include first), then by accession.
dec_rank <- c(include = 1, conditional = 2, exclude = 3)
tab <- tab[order(dec_rank[tab$decision], tab$accession), ]

dir.create("docs", showWarnings = FALSE)
write.csv(tab, "docs/triage.csv", row.names = FALSE)

# ---- Render docs/TRIAGE.md ----
md_row <- function(r) sprintf(
  "| [%s](../projects/%s/SUITABILITY.md) | %s | %s | %s | %s | %s | %s | `%s` | %s | **%s** |",
  r$accession, r$accession, r$organism, r$assay, r$n_samples, r$raw_counts,
  r$normalized, r$metadata, r$design, r$method, toupper(r$decision))

header <- c(
  "# Cross-dataset triage",
  "",
  "Auto-generated by `scripts/build_triage.R` from each project's",
  "`SUITABILITY.md` front-matter. Differential expression is run **only** for",
  "datasets with `decision: include`.",
  "",
  paste0("Datasets triaged: **", nrow(tab), "**  |  ",
         "include: ", sum(tab$decision == "include", na.rm = TRUE), ", ",
         "conditional: ", sum(tab$decision == "conditional", na.rm = TRUE), ", ",
         "exclude: ", sum(tab$decision == "exclude", na.rm = TRUE)),
  "",
  "| Dataset | Organism | Assay | n | Raw counts | Normalized | Metadata | Design | Method | Decision |",
  "|---------|----------|-------|---|-----------|-----------|----------|--------|--------|----------|")
body  <- vapply(seq_len(nrow(tab)), function(i) md_row(tab[i, ]), character(1))
footer <- c("", "## Decision rationale (lead reason per dataset)", "",
            vapply(seq_len(nrow(tab)), function(i)
              sprintf("- **%s** — %s: %s", tab$accession[i],
                      toupper(tab$decision[i]), tab$reason[i]), character(1)))

writeLines(c(header, body, footer), "docs/TRIAGE.md")
cat("Wrote docs/TRIAGE.md and docs/triage.csv (", nrow(tab), " datasets).\n", sep = "")
